#' @name rc_exportBundle
#' @title Perform a bundle of API calls.
#'  
#' @description Several of the API calls return objects that can be used to perform
#'   various validations in \code{rc_exportRecords}, \code{rc_exportReports}, and other
#'   methods.  Using an export bundle allows you to call these methods once and
#'   store the result instead of issuing an additional call to the API each 
#'   time a method is invoked.  
#'   
#'   For example, if you are uploading several files to the API, without an 
#'   export bundle, \code{importFiles} will utilize the \code{exportMetaData}
#'   on each call in order to perform validations.  Using a bundle allows you 
#'   to download the meta data once and refer to it on every subsequent call 
#'   that requires the data dictionary.
#'   
#' @param rcon A REDCap connection object as generated by \code{rc_connect}
#' @param meta_data Logical.  Indicates if the meta data (data dictionary) 
#'   should be exported.
#' @param users Logical. Indicates if the users table should be exported.
#' @param instruments Logical. Indicates if the instruments table should be exported.
#' @param events Logical. Indicates if the event names should be exported.
#' @param arms Logical. Indicates if the arms table should be exported.
#' @param mappings Logical. Indicates if the form-event mappings should 
#'   be exported.
#' @param version Logical. Indicates if the REDCap version number should be exported.  
#'   Only applicable in REDCap 6.0.0 and higher.
#' @param proj_info Logical. Indicates if the project information should be exported.
#' @param date Logical. If \code{TRUE}, user expiration dates are converted to 
#'   \code{POSIXct} objects.
#' @param label Logical.  If \code{TRUE}, the user form permissions are 
#'   converted to labelled factors.
#' @param ... Arguments to be passed to other methods
#' 
#' @details The project information is stored in the option 
#'   \code{redcap_project_info}.  If the project is not longitudinal, the 
#'   events, arms, and event-form mappings elements will be assigned character 
#'   vectors instead of data frames.
#'   
#' @author Benjamin Nutter
#' 
#' @export

rc_exportBundle <- function(rcon,  
                          meta_data=FALSE, users=FALSE, instruments=FALSE,
                          events=FALSE, arms=FALSE, mappings=FALSE,
                          proj_info=FALSE, version=FALSE,
                          date=TRUE, label=TRUE, ...){
  
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  massert(~ date + label + meta_data + users + instruments + 
            events + arms + mappings + version + proj_info,
          fun = checkmate::assert_logical,
          fixed = list(len = 1,
                       add = coll))
  
  checkmate::reportAssertions(coll)
  
  if (!any(meta_data, users, instruments, events, arms, mappings, proj_info, version)) {
    meta_data=TRUE
    users=TRUE
    instruments=TRUE
    events=TRUE
    arms=TRUE
    mappings=TRUE
    proj_info=TRUE
    version=TRUE
  }
  
  if (users) userData = exportUsers(rcon)
  
  bundle <- 
    structure(
      list(
        meta_data = if (meta_data) exportMetaData(rcon) else NULL,
        users = if (users) userData$Users else NULL,
        form_perm = if (users) userData$Form_Permissions else NULL,
        instruments = if (instruments) exportInstruments(rcon) else NULL,
        events = if (events) exportEvents(rcon) else NULL,
        arms = if (arms) exportArms(rcon) else NULL,
        mappings = if (mappings) exportMappings(rcon) else NULL,
        proj_info = if (proj_info) exportProjectInformation(rcon) else NULL,
        version = if (version) exportVersion(rcon) else NULL
      ),
      class = c("redcapBundle", "redcapProject", "list")
    )
  
  options(redcap_bundle = bundle)
  return(bundle)
}
